Allow more minimal cargo features & allow setting UDS filename
TeamPiped/piped-proxy pull request #90
Opened 2023-09-14 17:39 UTC by chaoticryptidz

This PR should allow for building without image transcode support.

It also allows for turning that off at runtime with the `DISALLOW_IMAGE_TRANSCODING` env variable for use on systems where image transcoding would be a CPU problem.

It also renames `UDS` env variable to `BIND_UNIX` where `BIND_UNIX` is set to the filename/path of the socket file, so you don't need to use a hardcoded default including a folder that may not exist at time of running.

It also allows for building with openssl/native-tls on linux by turning on the `reqwest-native-tls` feature.

It also allows for turning off mimalloc

Some other components and dockerfiles may need updating but I don't think UDS is enabled anywhere outside of a old version of my piped nixos flake.

This shouldn't break any existing docker-based piped install.

2023-09-22 10:14 UTC, FireMasterK requested changes
LGTM, just one small thing to preserve backwards compatibility.

2023-09-22 10:14 UTC, FireMasterK commented on src/main.rs
> +        server.bind_uds(unix_socket)?
Can we keep the UDS environment variable to enable binding to a UDS, and keep the BIND_UNIX variable to choose the file to bind to but default to the previous value if unset.

2023-09-27 20:42 UTC, chaoticryptidz commented on src/main.rs
> +        server.bind_uds(unix_socket)?
done, now uses the previous as default if BIND_UNIX isn't set

2023-09-29 12:02 UTC, FireMasterK approved these changes
Thank you!

2023-09-29 12:05 UTC, merged